version: "3.4"
services:
  netbox:
    image: netboxcommunity/netbox:v3.3.7
    ports:
      - 80:8080
    volumes:
    - ../netbox-media-files:/opt/netbox/netbox/media:z
  postgres:
    volumes:
    - ../netbox-postgres-data:/var/lib/postgresql/data
  redis:
    volumes:
    - ../netbox-redis-data:/data
